backend:
  name: github
  repo: boraiks/borakosalay
  branch: master

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: projects
    label: Projects
    files:
      - name: projects_list
        label: All projects
        file: data/projects.json
        fields:
          - label: Projects
            name: items
            label_singular: Project
            widget: list
            summary: "{{fields.title}}"
            fields:
              - { label: Title, name: title, widget: string }
              - { label: Date, name: date, widget: datetime, date_format: "YYYY-MM-DD", time_format: false, format: "YYYY-MM-DD", picker_utc: true }
              - { label: Category, name: category, widget: select, options: [Software, Hardware, Concepts, Article] }
              - label: Tags
                name: tags
                widget: relation
                collection: tags
                file: tags_list
                value_field: "items.*.name"
                search_fields: ["items.*.name"]
                display_fields: ["items.*.name"]
                multiple: true
                required: false
                options_length: 10000
              - { label: "Link (optional)", name: url, widget: string, required: false, default: "#" }

  - name: tags
    label: Tags
    files:
      - name: tags_list
        label: All tags
        file: data/tags.json
        fields:
          - label: Tags
            name: items
            label_singular: Tag
            widget: list
            summary: "{{fields.name}}"
            fields:
              - { label: Name, name: name, widget: string }
              - { label: Color, name: color, widget: color }
